<?php

namespace App\Enum;

class HistoryTypes
{
    const ECU_PARAMETER_MANAGEMENT = 1;
    const VEHICLE_CONFIGURATION_SVC_MANAGEMENT = 2;
    const VEHICLE_CONFIGURATION_VC_MANAGEMENT = 3;
    const COC_VALUES_SETS_ASSIGNMENT = 4;
    const SOFTWARE_MANAGEMENT = 5;
}